{% set version = "0.3.0" %}

package:
  name: phreeqpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/phreeqpy/phreeqpy-{{ version }}.tar.gz
  sha256: 8ffbf61ee1ae7c8fb4474dcb7e40f48e24d920375253bb83f47f6d67bc3f70b8

build:
    number: 1
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - phreeqpy
    - phreeqpy.iphreeqc

about:
  home: http://www.phreeqpy.com/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python tools for PHREEQC

extra:
  recipe-maintainers:
    - ocefpaf
