# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "QZZNKybkDAP4yf+qlb+cCwH8pSLuvG7r3tcZF+pf34CO2USontNY/bwZPaxoIOnavBSaC9ph7Mn2BuYwNU1FC1swfoDL8Lg0zTuBbJIM77ZxgWUw9Prb3O4/592zLFTxT8qVgJ7PR2c+h+xPmt/xlTd19PYM1BK1v2I5UXm7fXVZ7A+K0kVNPBXGfooldIfgVXeD/iO6WBW3m9MZrChHlsnYc8zSSq5oryIhr6FZX/ZL2vrDNuVNKyqXONDG1QMjtXav7DRXVKbQ20sOUfMwhD7CCeg27jt1wCAMi0CDORY9kWLalGpQ677+lWLbB2vy6NRGvUYgyoFqyjFl9721TzQLUtkO4qWVy7Gnq6Sp6vpjt7D/5pb9giSh8f0ZLI15c1lWLtOwT2sjowc42tll+BxeI+HFcq/h4QRSwP4eB/zAvKaCsKHSaJVpOqbjY7pjco0EdxfKI6hortiTAs6ws0daSyjK4cpS4zCoDag0z0snzQpLHRxwpXD/ipAazH9E/mEH8pjVwZhqwIR+2CcjLqktzbIuU27cCXAvpco49ez1+ekjk27tIQgQyWzHOowpY+DA87Jk88HNg+5HPlTVC4fnkc/QXiA9jCe4MWHIUG+GbhaVJB4fveH/Yz7JemT09GRUPDinnJCeKNzd71Xr6yLKL1QVmDhE0vg3asUKIaE="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
