travis:
  secure:
    BINSTAR_TOKEN: VfM5DsktcPxmNYWA23YD/Xnf04XQLqSW7WSWxPgzitbys5dbVvIS4HZMAiqGKkA08GgiIxNNsfNS07dmHmX5PlTNKu55j68squwn54rZr+0VLA2h7P/9rXqO3K4utSoayb+iAEItd9kYZJPzCsZiHgojXycE7W9Z0jtMlE9rIrtgz1QTR0QHD12QHOMlu5vtYQ1o9OD/sGU/fv8TH4+WglTi8oIbb+tChFQ/zgpdmoRluOMpjRdbvWOksAJ72uSa23uyzzx1UNmwke0j+HhlSQXwPhQTRpc6uZ0YTLULrYGGRBFaWTFXfTK2Hi6nDJ24a59LLz7xvUkP1ajU9r4Yh+OVXQdVOPX1lWaNR2w7xfRF9Xspb4pMoZThDkJBuHKym2HRQ1dw2X27lOc0rBYqj4tbsnCR5bxr3lEB+ovle93k19KoBrqKlRmn0hGOfO/sY9cy6WpnojNPrCduZivIXxtYTcak8OQFiOwXt+hjpNpZXIdyOdaui6w0Ao1Ib6fwiw9/EeOt6+j/AzNzwYZ170VmexCIh9wdsU6necg7RhkemXuiSmcIFbqap/2huYeZFkjU3p7MzT9n2JVdKCQ1HTbVzy0WGm0DOf0bUEClr51qAQvQ1unNrznPL3nSUQxbQxNykeGVyfMJBQONz4MpPDTbBLP+/z/gJ7meKAiiFds=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
