travis:
  secure:
    BINSTAR_TOKEN: QZZNKybkDAP4yf+qlb+cCwH8pSLuvG7r3tcZF+pf34CO2USontNY/bwZPaxoIOnavBSaC9ph7Mn2BuYwNU1FC1swfoDL8Lg0zTuBbJIM77ZxgWUw9Prb3O4/592zLFTxT8qVgJ7PR2c+h+xPmt/xlTd19PYM1BK1v2I5UXm7fXVZ7A+K0kVNPBXGfooldIfgVXeD/iO6WBW3m9MZrChHlsnYc8zSSq5oryIhr6FZX/ZL2vrDNuVNKyqXONDG1QMjtXav7DRXVKbQ20sOUfMwhD7CCeg27jt1wCAMi0CDORY9kWLalGpQ677+lWLbB2vy6NRGvUYgyoFqyjFl9721TzQLUtkO4qWVy7Gnq6Sp6vpjt7D/5pb9giSh8f0ZLI15c1lWLtOwT2sjowc42tll+BxeI+HFcq/h4QRSwP4eB/zAvKaCsKHSaJVpOqbjY7pjco0EdxfKI6hortiTAs6ws0daSyjK4cpS4zCoDag0z0snzQpLHRxwpXD/ipAazH9E/mEH8pjVwZhqwIR+2CcjLqktzbIuU27cCXAvpco49ez1+ekjk27tIQgQyWzHOowpY+DA87Jk88HNg+5HPlTVC4fnkc/QXiA9jCe4MWHIUG+GbhaVJB4fveH/Yz7JemT09GRUPDinnJCeKNzd71Xr6yLKL1QVmDhE0vg3asUKIaE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
