appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LXyD8RY2Vg3OH/UjkEuhQk4solo4PG8lOJF+vpo92V+b8d//wkri3sn+p3q0inkNSx5g33CFItY7sd9DFnCBV76adVdarHup8w2pTIDWmnxl5fWeYQZHzRlPjQSPC+anFi9fatV4SqAG26S+B6Fguyf0jRdldDO5FSp6btcZXA6N1ZZolWVT+EZVEkr5FfH+guIE9ZDjeogDF0yBF7SIrvObAeEMNWFMtJgfyyJjPVpPKaYIB+xbmAmvaZH37Li+2l5/AGEYJr23+BOugCJqN23ZwORCDzmCmVSDewOn1YnbiHSP9eJ7Vyn49MQgQoWGnuBQFCQTEmpr9+LHmqwGPfC70rPFsNlbfpo7SddIc31c9mdMG9y5RUFUOMbsOfyQ6bC/wUzDPiZpTdbV1XqRGEuh8MuwkFshov3USs/59HieUmHDzciMJcFBvbFnTLrUH7Sb8IZmBe+z3tlYjg4sKhAtvVU9Z+N872nsF0F6L6t3YVBxrg2CAEB6e438O7KAaRwwNu/eY+2UkieS9rMg2iM05FnlQjsQGCZfcB1+LSLvl0pDXjDCWQvCEIX2roJlyKcG4+hsdKgRH0u3TAeWlnGckTS0otYgyQJGTEYMLanTcaLX/ArD4qmK+2XlzqSDJ+6Acbase30+Url48neXlWAhATeLbNUhdfl/pvKt0tE=}
provider:
  win: azure
